### ISSUE TITLE
Not sincronize with bookmark-alist

### ISSUE THREAD

**Issue by Brusten** [joodland/bm#18]
Hello,

The function `ivy-switch-buffer` use the build in variable `bookmark-alist` to incorporate bookmarks to its options, but with `bm` the variable `bookmark-alist` has always nil value.
The code `(load-bookmark bm-repository-file)` says that the `bm-repository-file` is not in the "standard form".

Is there a way to get `bookmark-alist` syncronized with `bm-repository-file` or at least a way to get a file in "standard form" with the bookmarks of `bm-repository-file`??

Thank you very much.

**Comment by joodland** [comment]
Hi,

There is no connection between the original bookmarks feature in Emacs and bm.el, thus the `bookmark-alist` will always be nil. I do not want to add synchronisation between the two features, because it will be hard to always keep the two systems in sync.

It is possible to make a hack that do add some synchronisation between standard bookmark.el and bm.el by advising the functions `bm-bookmark-add` and `bm-bookmark-remove`, but I do not give any guarantees that this do not have any side effects.

A code example is provided below:

```
(defun bm-bookmark-add--sync (&optional annotation time temporary-bookmark)
  "Add a standard Emacs bookmarks when setting a bm-bookmark."
  ;; create a unique name for the bookmark
  (let ((name (concat (buffer-name)     
                      " l:" (int-to-string
                             (count-lines (point-min) (point))))))
    ;; store the bookmark name as an annotation
    (bm-bookmark-annotate (bm-bookmark-at (point)) name)
    (bookmark-set name)))

(advice-add 'bm-bookmark-add :after #'bm-bookmark-add--sync)


(defun bm-bookmark-remove--sync (&optional bookmark)
  "Remove a standard Emacs bookmarks when setting a bm-bookmark."
  (if (null bookmark)
      (setq bookmark (bm-bookmark-at (point))))

  (if (bm-bookmarkp bookmark)
      ;; delete bookmark by name (from annotation)
      (bookmark-delete (overlay-get bookmark 'annotation))))

(advice-add 'bm-bookmark-remove :before #'bm-bookmark-remove--sync)

```

**Comment by Brusten** [comment]
Thank you very much, I didn't know it.
And thanks for the code, it works fine but not for my purposes.
